matrix:
  include:
    - language: python
      python: 3.8
      before_script:
        - cd scn_h5_converter
        - pip install -r requirements.txt
        - export PYTHONPATH=$PYTHONPATH:`pwd`
      script: pytest tests --typeguard-packages=converter

    - language: java
      services:
        - mongodb
      env:
        - MONGODB_HOST=127.0.0.1:27017
        - MONGODB_DATABASE=scn
        - MONGODB_COLLECTION=datasets
        - PROD_PATH=/home/travis/build/ctlab/scNavigator/scn_js/prod
      jdk:
        - openjdk8
      script:
        - gradle build

    - language: node_js
      node_js:
        - "11"
        - "10"
      env:
        - CXX=g++-7
      before_script:
        - cd scn_js
      scipt: npm install && npm run build

notifications:
  email:
    - zayats1812@mail.ru

