version: '2'

services:
  nginx:
    build: ./nginx
    depends_on:
      - web
    volumes:
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./scn_js:/scn/scn_js"
      - "$TMP_PATH:/var/tmp"
    ports:
      - "31:80"

  genequery:
    container_name: gq
    depends_on:
      - fs
    restart: always
    build: ./genequery
    expose:
      - 8423
    ports:
      - "8423:8423"
    volumes:
      - "$GMT_PATH:/genequery/data-files"


  mongo:
    image: mongo:latest
    restart: always
#    ports:
#      - "27017:27017"
    volumes:
      - "./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
      - "$DATASET_PATH:/var/datasets"

  fs:
    restart: always
    depends_on:
      - mongo
    build: ./scn_h5_converter
    volumes:
      - "$DATASET_PATH:/var/datasets"
      - "$TMP_PATH:/var/tmp"
      - "$GMT_PATH:/vat/gmt"
    command: [ "python", "./watcher/Watcher.py", "/var/datasets", "/var/tmp", "/vat/gmt",
               $MONGODB_HOST, $MONGODB_DATABASE, $MONGODB_COLLECTION]

  web:
    env_file:
      - .env
    restart: always
    depends_on:
      - fs
    build: ./scn_server
    volumes:
      - "$DATASET_PATH:/var/datasets"
      - "./scn_js:/scn/scn_js"
      - "$TMP_PATH:/var/tmp"
    command: ["java", "-Djava.library.path=./", "-jar", "server.jar"]
