version: '2'

services:
  nginx:
    build: ./nginx
    depends_on:
      - web
    restart: always
    volumes:
      - "./nginx/sites-enabled:/etc/nginx/sites-enabled"
      - "./scn_js:/scn/scn_js"
      - "./scn_docs/build/:/scn/docs"
      - "$DATASET_PATH:/var/datasets"
    ports:
      - "3133:80"

  genequery:
    depends_on:
      - fs
    restart: always
    build: ./genequery
    expose:
      - 8423
    ports:
      - "8433:8423"
    volumes:
      - "$GMT_PATH:/genequery/data-files"


  mongo:
    image: mongo:latest
    restart: always
#    ports:
#      - "27033:27017"
    volumes:
      - "./mongo/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
      - "$DATASET_PATH:/var/datasets"
  fs:
    env_file:
      - .env
    restart: always
    depends_on:
      - mongo
    build: ./scn_fs
    volumes:
      - "$DATASET_PATH:/var/datasets"
      - "$GMT_PATH:/vat/gmt"
      - "$TMP_PATH:/var/tmp"
    command: ["java", "-Djava.library.path=./", "-jar", "fs.jar", "/var/datasets", "/vat/gmt", "All Files/test_dir", "$BOX_DEV_KEY"]

  web:
    env_file:
      - .env
    restart: always
    depends_on:
      - fs
    build: ./scn_server
    volumes:
      - "$DATASET_PATH:/var/datasets"
      - "./scn_js:/scn/scn_js"
    command: ["java", "-Djava.library.path=./", "-jar", "server.jar"]

  rclone_fs:
    env_file:
      - .env
    restart: always
    depends_on:
      - fs
    image:  rclone/rclone
    volumes:
      - "~/.config/rclone:/config/rclone"
      - "~/data:/data:shared"
      - "/etc/passwd:/etc/passwd:ro"
      - "/etc/group:/etc/group:ro"
    user: $(id -u):$(id -g)
    ports: "5533:5572"
    device: "/dev/fuse --cap-add SYS_ADMIN --security-opt apparmor:unconfined"
    command: ["rclone", "--vfs-cache-mode full", "--cache-dir ~/box-cache", "--vfs-cache-max-age 10h", 
    "--vfs-cache-poll-interval 120s", "--vfs-read-ahead 20M", "--buffer-size 2000M",  "--vfs-disk-space-total-size 10G", 
    "mount remote:/test_dir ~/box_dir",
    "--read-only", "--dir-cache-time 5m", "--poll-interval 60s",
    "--allow-non-empty", "--allow-other", "-v", "--rc", "--rc-addr :5572"]