name: Java CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mongodb-version: [3.6, 4.0, 4.2, 4.4]

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}
      - name: Build with Gradle
        run: ./gradlew build
        env:
          MONGODB_HOST: 127.0.0.1:27017
          MONGODB_DATABASE: scn
          MONGODB_COLLECTION: datasets
          PROD_PATH: /home/travis/build/ctlab/scNavigator/scn_js/prod